---

- name: Copy the essentials config.yml file
  ansible.builtin.copy:
    src: "src_files/essantials_config.yml"
    dest: "{{ working_dir }}/plugins/Essentials/config.yml"

- name: Copy the jobs config.yml file
  ansible.builtin.copy:
    src: "src_files/jobs_config.yml"
    dest: "{{ working_dir }}/plugins/Jobs/generalConfig.yml"

- name: Copy the jobs config.yml file
  ansible.builtin.copy:
    src: "src_files/worldguard_regions_config.yml"
    dest: "{{ working_dir }}/plugins/WorldGuard/worlds/world/regions.yml"

- name: Copy the Luckperms config.yml file
  ansible.builtin.copy:
    src: "src_files/luckperms_config.yml"
    dest: "{{ working_dir }}/plugins/LuckPerms/config.yml"

- name: Copy the Kits file
  ansible.builtin.copy:
    src: "src_files/kits.yml"
    dest: "{{ working_dir }}/plugins/Essentials/kits.yml"

- name: Copy the spawn file
  ansible.builtin.copy:
    src: "src_files/spawn.yml"
    dest: "{{ working_dir }}/plugins/Essentials/spawn.yml"

- name: Copy the server.properties file
  ansible.builtin.copy:
    src: "src_files/server.properties"
    dest: "{{ working_dir }}/server.properties"

- name: Copy the server pp file
  ansible.builtin.copy:
    src: "src_files/server_pp"
    dest: "{{ working_dir }}/server-icon.png"

- name: Copy the server permissions file
  ansible.builtin.copy:
    src: "src_files/permissions.yml"
    dest: "{{ working_dir }}/permissions.yml"